theme: Minimal

# Site settings
title: 静心学堂
description: 三级修学资料
url: "https://mindfulpeace.github.io/" # 你的站点 URL
baseurl: "" # 站点的子路径（如果有）

# Author settings
author:
  name: 智展
  email: rjintao@gmail.com

# Social settings
social:
  # twitter: your_twitter_username
  github:  mindfulpeace
 # linkedin: your_linkedin_username

# Build settings
markdown: kramdown
highlighter: rouge

# Minima theme settings
minima:
  # Enable dark mode
  skin: dark

  # Enable header links
  header_links:
    - title: "Home"
      url: "/"
    - title: "同喜"
      url: "/同喜"
    - title: "同修"
      url: "/同修"

  # Enable footer links
  footer_links:
    - title: "Privacy Policy"
      url: "/privacy-policy"
    - title: "Terms of Service"
      url: "/terms-of-service"